### ISSUE TITLE
Get Date Selected Using onDayClick

### ISSUE THREAD

**Issue by thekendog** [benitolopez/hotel-datepicker#99] opened 2021-03-29 16:51 UTC
Is it possible to get the date selected when using the onDayClick event?  Also, it doesn't look like the getValue method updates until start and end dates have been selected.  I'm trying to use it within onDayClick when only the start date has been selected.  Any way to make that work?

Essentially, I'm trying to make this work with a check-in and check-out field instead of one single field.

**Comment by benitolopez** [comment] 2021-03-29 19:08
Hello,

As per documentation:
`getValue()`: This function is called when the picker gets the date range string from the input.

It can be used to modify the datepicker when it reads the input value. It is not a method meant to be used when the input is empty.

You can get the start and end values with `yourDatepickerVar.start` and `yourDatepickerVar.end`. This should work with onDayClick().

Unfortunately, I'm not able to provide support for custom integrations of the library. So I'm closing this issue because it is not a bug.

**Closed by benitolopez** 2021-03-29 19:08 UTC
