### ISSUE TITLE
Calendar display in mobile

### ISSUE THREAD

**Issue by sarags** [benitolopez/hotel-datepicker#182] opened 2024-02-12 18:41 UTC
Thank you so much for this library, it's amazing !

I'm having a issue with mobile, not sure it's a issue but i'm using the datepicker to display the 2 months in a vertical way and when in mobile i only have one month.
Is it possible to still display 2 months calendar in mobile ? some workaround or configuration?

Thank you

**Comment by benitolopez** [comment] 2024-02-13 22:11
Hello,

You can do it with CSS.

The datepicker comes with an unsupported base CSS, but it is recommended that you modify it according to your needs.

I don't have a specific suggestion, but the second month is hidden via CSS (https://github.com/benitolopez/hotel-datepicker/blob/main/src/sass/_base.scss#L60), so you can start from there.

I'm closing this issue because it is not a bug.

**Closed by benitolopez** 2024-02-13 22:11 UTC

**Comment by sarags** [comment] 2024-02-14 10:19
Thank you !
