### ISSUE TITLE
Issue with noCheckOutDates in reverse order in v4.3.3

### ISSUE THREAD

**Issue by JordyGit** [benitolopez/hotel-datepicker#133] opened 2022-08-08 17:10 UTC
#127 is fixed in normal order, but some cases that should be allowed in reverse order (with `selectForward: false`) are now disabled that shouldn't.

Gif:
![StillSmallBugWithNoCheckInOutDatesInReverseOrder](https://user-images.githubusercontent.com/33500507/183474704-ef4d7606-be32-455f-a09a-2b51bb92692b.gif)

Code:
```
var rangePicker = new HotelDatepicker(pickerEl, {
		inline: true,
		clearButton: true,
		submitButton: true,
		topbarPosition: 'bottom',
		submitButtonName: 'name_of_submit_button',
		moveBothMonths: true,
		selectForward: false,
		startOfWeek: 'monday',
		endDate: maxDate,
		format: 'DD/MM/YYYY',
		noCheckInDates: [
			'2023-07-03'
		],
		noCheckOutDates: [
			'2023-07-04'
		]
	});
```

**Comment by benitolopez** [comment] 2022-08-08 18:16
Seems that the problem is related to the `noCheckOutDates` only. Can you confirm? `noCheckInDates` is working correctly from your gif.

**Comment by JordyGit** [comment] 2022-08-08 18:48
Yes indeed, after watching it again, you are right

**Comment by benitolopez** [comment] 2022-08-08 22:03
Fixed in https://github.com/benitolopez/hotel-datepicker/commit/82cca4526045acf005fcf038d3a5f2cdd2acc527

**Closed by benitolopez** 2022-08-08 22:03 UTC
