### ISSUE TITLE
Change options dynamically

### ISSUE THREAD

**Issue by jo-goburdhun** [benitolopez/hotel-datepicker#101] opened 2021-05-19 09:08 UTC
Is it possible to change options of the datepicker dynamically? For example I need to be able to change the `endDate` depending on the check-in date the user is selecting.

    let input            = $("#datepickerInput").get(0),
        container        = $("#datepickerContainer").get(0),
        datepickerPlugin = new HotelDatepicker(input, {
            container: container,
            autoClose: false,
            selectForward: true,
            preventContainerClose: true,
            onDayClick: function () {
                let checkIn           = $('.datepicker__month-day--first-day-selected'),
                    firstDisabledElem = checkIn.nextALL(".datepicker__month-day--day-of-week-disabled:first"),
                    monthYear         = firstDisabledElem.parent().parent().prev().find('.datepicker__month-name').text().split(" "),
                    firstDisabledDate = firstDisabledElem[0].innerText + '-' + months[monthYear[0]] + '-' + monthYear[1];

                $(this)[0].endDate = fecha.parse(firstDisabledDate, $(this)[0].format);

                console.log($(this));
            },          
            disabledDaysOfWeek: disabledDays,
            minNights: 1,
            moveBothMonths: true,
            format: 'DD-MM-YYYY',
            separator: '~'
        });
    datepickerPlugin.open();

**Comment by benitolopez** [comment] 2021-05-19 13:24
Hello,

There is no such option. This is something you need to integrate yourself via JS. 

Unfortunately, I can't help you, but maybe someone has some suggestions. In any case, I have to close the issue because this is not a bug.

**Closed by benitolopez** 2021-05-19 13:24 UTC
