### ISSUE TITLE
select one day

### ISSUE THREAD

**Issue by juliette-bois** [benitolopez/hotel-datepicker#162] opened 2023-03-13 20:20 UTC
Hello,

Is it possible to allow the user to select only 1 day ?

**Comment by benitolopez** [comment] 2023-03-13 22:54
This is not possible.

Duplicate of https://github.com/benitolopez/hotel-datepicker/issues/108 and https://github.com/benitolopez/hotel-datepicker/issues/31

**Closed** 2023-03-13 22:55 UTC
