### ISSUE TITLE
Feature request: minNights depending on a certain timeframe

### ISSUE THREAD

**Issue by Maxximus007** [benitolopez/hotel-datepicker#178] opened 2024-01-10 10:55 UTC
Hi, the minNights is a great option to prevent one night (party) stays. At times it is unfortunate that this is valid for the whole calendar.
In my case I would like to have another control: be able to change the minNights for certain weeks, while the default is set to minNights.

For example:
minNights: 3
minNightsExceptions: { 31: 7, 32: 7, 33: 5, 41: 2 }

I've used weeks here, but to broaden the use it could be date ranges as well. 

Thanks for considering!

**Comment by benitolopez** [comment] 2024-01-10 11:26
Duplicate of https://github.com/benitolopez/hotel-datepicker/issues/175

It is already on my agenda, but I didn't have the time to implement it.

**Closed by benitolopez** 2024-01-10 11:26 UTC

**Comment by Maxximus007** [comment] 2024-01-10 13:28
Sorry for that, saw all issues closed, and looked no further ;).
